version: '3'
services:
  ldap_server:
    build:
      context: ./docker
    environment:
      LDAP_ADMIN_PASSWORD: symfony
      LDAP_BASE_DN: "dc=symfony,dc=com"
      LDAP_SEED_INTERNAL_LDIF_PATH: "/ldif-data"
    ports:
      - 389:3389
  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
